### ISSUE TITLE
FLOPs on ADE20K dataset seems to be too large?

### ISSUE THREAD

**Issue by bowenc0221** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#16]
The FLOPs reported in the paper seem to be too large, I'm wondering what is the input size when you calculate the FLOPs?

When I calculate the FLOPs for Swin-Tiny model with the command:
```
python tools/get_flops.py configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k.py --shape 512 512
```

I got the following output:
```
==============================
Input shape: (3, 512, 512)
Flops: 236.08 GFLOPs
Params: 59.94 M
==============================
```

But in the paper, Swin-Tiny has 945G FLOPs.

Could you share more details on how you calculated the FLOPs in your paper? Thanks!

**Comment by zeliu98** [comment]
Hi, we use 512x2048 input size to calculate the FLOPs.
