### ISSUE TITLE
KeyError: 'SwinTransformer is not in the models registry'

### ISSUE THREAD

**Issue by kartikwar** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#20]
getting this error
 **KeyError: 'SwinTransformer is not in the models registry'**

on running the command 
**python tools/test.py configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k.py models/upernet_swin_base_patch4_window7_512x512.pth --eval mIoU**

Can someone help ?

**Comment by kartikwar** [comment]
Also I used the dockerfile provided at https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation/blob/main/docker/Dockerfile to run the above command

**Comment by apple1986** [comment]
I meet the same problem, can anyone help?

**Comment by kartikwar** [comment]
hey @apple1986 I have added the instructions at the forked repo https://github.com/kartikwar/Swin-Transformer-Semantic-Segmentation

**Comment by kartikwar** [comment]
Closing this issue as it is resolved now

**Comment by github-luffy** [comment]
> I meet the same problem, can anyone help?
SwinTransformer是自定义的backbone，安装mmsegmentation的时候不能安装原来GitHub上的，可以直接pip install -e . 的命令安装。
