### ISSUE TITLE
the result of  swin base segmentation is 49.72% mIoU, is it used pretrained model imagenet-1k or imagenet-22k?

### ISSUE THREAD

**Issue by Sunting78** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#29]
the result of  swin base segmentation is 49.72% mIoU, i see the pretrain=None in the config. So, this result is not used pretrained model,  right?

**Comment by impiga** [comment]
Sorry for the misleading config. 

All results in [this table](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation#ade20k) use models pre-trained on ImageNet-1K.
