### ISSUE TITLE
meet the issue KeyError: 'backbone.layers.0.blocks.0.attn.relative_position_bias_table'

### ISSUE THREAD

**Issue by panda-2014** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#3]
when I train my own datasets, meet the issue as below:
KeyError: 'backbone.layers.0.blocks.0.attn.relative_position_bias_table

environment:
rtx3090 4 GPU(rtx3090) with cuda 11.1 
swin-b 
upernet_swin_base_patch4_window7_512x512.pth
may somebody give any clues?

**Comment by impiga** [comment]
Hi, "upernet_swin_base_patch4_window7_512x512.pth" is a model finetuned on ADE20K, not an ImageNet pre-trained model.
You would better use pre-trained models held in [this page](https://github.com/microsoft/Swin-Transformer#main-results-on-imagenet-with-pretrained-models).

**Comment by walynlee** [comment]
@panda-2014 Hello, could you tell me the run code when training on one gpu on windows(RTX 3090)? I need it as an example to train the model.

**Comment by panda-2014** [comment]
> @panda-2014 Hello, could you tell me the run code when training on one gpu on windows(RTX 3090)? I need it as an example to train the model.

I run on linux, and the I have change to run on rtx8000x4 GPU, and occur some new issues. I still have no idea about the issue :(

**Comment by Leesanjin** [comment]
Do you have to solve this problem?I also met the same problem

**Comment by JiachunWang** [comment]
@panda-2014 I also met the same problem. This is because of the inconsistency of the state_dict.keys(). Strip the prefix of state_dict can solve the problem. I've solved the problem by adding the following codes in mmsegmentation/mmcv_custom/checkpoint.py:line 322
`    if list(state_dict.keys())[0].startswith('backbone.'):
        state_dict = {k[9:]: v for k, v in state_dict.items()}`

**Comment by CeciliaPYY** [comment]
512 pretrained model can be found here: https://github.com/open-mmlab/mmsegmentation/tree/master/configs/swin
