### ISSUE TITLE
AttributeError: 'super' object has no attribute '_specify_ddp_gpu_num'

### ISSUE THREAD

**Issue by litc-rgb** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#37]
Thank you very much ,I have a question to ask you .
configuration 0f my enviroment
mmcv-full          1.2.4
mmsegmentation     0.11.0
my problem:
AttributeError: 'super' object has no attribute '_specify_ddp_gpu_num'

**Comment by SanghoonKim918** [comment]
How did you solved this?

**Comment by litc-rgb** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
