### ISSUE TITLE
Unexpected keyword argument 'ape'

### ISSUE THREAD

**Issue by TNA8** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#50]
When I run a demo using a pretrained model, I faced an error.
What I run is
`python demo/image_demo.py test.png configs/swin/upernet_swin_tiny_patch4_window7_512_512_160k_ade20k.py moby_upernet_swin_tiny_patch4_window7_512*512.pth`

Error is
![screenshot_4](https://user-images.githubusercontent.com/58914448/139528706-f882d49a-0bf4-4cd0-9b75-d939fe729138.png)

**Comment by miaochunle** [comment]
I also encountered the same problem. How did you solve it

**Comment by Joseph-149** [comment]
Reference issue 4, maybe the enviroment is incompatible. I solve it in the following way.
cd Swin-Transformer-Semantic-Segmentation
pip install -e .
