### ISSUE TITLE
About pretrain model

### ISSUE THREAD

**Issue by Lsz-20** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#52]
Thanks for swin code ,it's more easier for me to read and run,but it's result always not good.
I'm using official offered pre-train model ‘upernet_swin_tiny_patch4_window7_512x512.pth’ & ‘swin_tiny_patch4_window7_224.pth’，but it seems not work well？
it shows these:
![image](https://user-images.githubusercontent.com/60343452/141257545-831a5b86-ef3c-4e5e-a292-fd6f0704911c.png)

Thanks

**Comment by impiga** [comment]
Hi, `swin_tiny_patch4_window7_224.pth` is the model pre-trained on ImageNet, while `upernet_swin_tiny_patch4_window7_512x512.pth` is the one fine-tuned on ADE.

If you would like to use ‘swin_tiny_patch4_window7_224.pth’ as initialization, you should use 
```
--options model.pretrained=/path/to/swin_tiny_patch4_window7_224.pth
```

If you would like to use `upernet_swin_tiny_patch4_window7_512x512.pth`, you can use
```
--load-from /path/to/upernet_swin_tiny_patch4_window7_512x512.pth
```

**Comment by Lsz-20** [comment]
> Hi, `swin_tiny_patch4_window7_224.pth` is the model pre-trained on ImageNet, while `upernet_swin_tiny_patch4_window7_512x512.pth` is the one fine-tuned on ADE.
> 
> If you would like to use ‘swin_tiny_patch4_window7_224.pth’ as initialization, you should use
> 
> ```
> --options model.pretrained=/path/to/swin_tiny_patch4_window7_224.pth
> ```
> 
> If you would like to use `upernet_swin_tiny_patch4_window7_512x512.pth`, you can use
> 
> ```
> --load-from /path/to/upernet_swin_tiny_patch4_window7_512x512.pth
> ```
Thanks for your replay~perhaps I have know their differences from your answer

**Comment by impiga** [comment]
Glad to hear that.
