### ISSUE TITLE
 According to the training steps, the result of Miou = 44.06 given by the author is not obtained, and the result is only 39.21

### ISSUE THREAD

**Issue by guohao02** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#53]
According to the training steps, the result of Miou = 44.06 given by the author is not obtained, and the result is only 39.21
![image](https://user-images.githubusercontent.com/80331072/141717084-233c7481-0686-4db4-bb0d-ca3b25bca410.png)

**Comment by impiga** [comment]
Hi, could you post the command you used?

**Comment by impiga** [comment]
This issue is closed due to inactivity for a long time. Feel free to open a new one if you have any question.
