### ISSUE TITLE
Problems in result reproduction on ADE20k with Swin-Tiny

### ISSUE THREAD

**Issue by slacklife** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#54]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
(1)
I get the final result on ade20k is as follows on ADE20k with Swin-T.

+--------+-------+-------+-------+
| Scope  | mIoU  | mAcc  | aAcc  |
+--------+-------+-------+-------+
| global | 45.65 | 56.16 | 82.04 |
+--------+-------+-------+-------+

I got the result mIoU=46.65, which is close to mIoU= 45.81 in [GitHub](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation#ade20k) but there is still a gap with mIoU=46.1 in Table3 of  original paper.
I don't know the reason and the details are as follows.

(2) I also want to know why the results published in [GitHub](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation#ade20k) are different from those published in paper (Table3).

(3)  The mIoU of Swin-S is 49.47 and Swin-B is 49.72 on ADE20k.
The difference is small and not as obvious as that in the paper (Table3: 49.3 VS 51.6).
What is the pretrained model (on imagenet-1k or imagenet-20k) used when training the Swin-B on ADE-20k?

Many thanks.

**Reproduction**

1. What command or script did you run?
```
cfg=configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k.py
pretrain=buffer/pretrain/swin_tiny_patch4_window7_224.pth
gpunum=8
sh tools/dist_train.sh \
    $cfg \
    $gpunum \
    --options model.pretrained=$pretrain
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
no

3. What dataset did you use?
ade20k

**Environment**
1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.

```
sys.platform: linux
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (GCC) 6.4.0 20170704 (Red Hat 6.4.0-1)                                                                                                PyTorch: 1.8.0                                                                                                                                 PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications                          - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)                                                                  - OpenMP 201511 (a.k.a. OpenMP 4.5)                                                                                                            - NNPACK is enabled                                                                                                                            - CPU capability usage: AVX2                                                                                                                   - CUDA Runtime 11.1                                                                                                                            - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c
++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PY
TORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-ar
ray-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unuse
d-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=peda
ntic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-unin
itialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WI
TH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_
MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0
OpenCV: 4.5.4
MMCV: 1.3.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMSegmentation: 0.11.0+87e6f90
```

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
```
conda install pytorch, the command is from the official webset of pytorch
```

    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```
none
```

**Bug fix**
```
none
```

**Comment by impiga** [comment]
Thank you for your interest.

1. Why results in GitHub are different with those in paper?
All results in paper were produced with our internal repos. After paper submission, we cleaned our code base and re-runed all the experiments, including ImageNet pre-training and ADE finetuning. So the results may be slightly different with those in paper. 

2. Swin-Tiny achieves 45.65 mIoU, which is close with the result in GitHub (45.81) but has a gap with that in paper (46.1)
As stated in the previous question, the different results of GitHub and paper may stem from different pre-trained model and codes. In addition, I think 45.65 mIoU is a good re-produced result of 45.81 mIoU.  

3. Pre-trained model of Swin-Base
As the caption of Table 3 illustrates, the Swin-Base model in Table-3 are pre-trained on ImageNet-22K.
However, we only release segmentation models pre-trained on ImageNet-1K now. There is an obvious performance gap (49.72 vs. 51.6), showing the effectiveness of ImageNet-22K pre-training.

**Comment by shangshang0912** [comment]
您的邮件已经收到。我会及时做出回复。

**Comment by impiga** [comment]
This issue is closed due to inactivity for a long time. Feel free to open a new one if you have any question.
