### ISSUE TITLE
How to load the pretrained model ?

### ISSUE THREAD

**Issue by David-zaiwang** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#7]
Dear authors:
first, great thanks for your excellent work. 
When I want to train the model for my custom datasets with one single GPU, I run the following code:
`python tools/train.py configs/swin/upernet_swin_base_patch4_window7_512x512_160k_messidor.py --options model.pretrained=weights/upernet_swin_base_patch4_window7_512x512.pth`

the error occurs: KeyError: "EncoderDecoder: 'backbone.layers.0.blocks.0.attn.relative_position_bias_table'"

So, how to solve it?

**Comment by impiga** [comment]
Hi, @David-zaiwang .  "upernet_swin_base_patch4_window7_512x512.pth" is a model finetuned on ADE20K, not an ImageNet pre-trained model.
You would better use pre-trained models held in [this page](https://github.com/microsoft/Swin-Transformer)

**Comment by AnukritiSinghh** [comment]
Hi @David-zaiwang what command did you exactly use then to fine tune on your custom dataset? 
Thanks

**Comment by xuhao-anhe** [comment]
> Hi @David-zaiwang what command did you exactly use then to fine tune on your custom dataset? Thanks

Hello, have you solved this problem

**Comment by Lsz-20** [comment]
@David-zaiwang @AnukritiSinghh @xuhao-anhe  the same question!have you solved this question?
@impiga It seems that these pretrain offered by official swin cannot work well on this code?

**Comment by impiga** [comment]
For people having the same issue~

Please try to use this command:
```
python tools/train.py \
  configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k.py \
  --options \
  model.pretrained=swin_base_patch4_window7_224.pth
```

The ImageNet pre-trained model `swin_base_patch4_window7_224.pth` can be downloaded from [this table](https://github.com/microsoft/Swin-Transformer/blob/main/get_started.md#regular-imagenet-1k-trained-models)

**Comment by dongfeicui** [comment]
> For people having the same issue~
> 
> Please try to use this command:
> 
> ```
> python tools/train.py \
>   configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k.py \
>   --options \
>   model.pretrained=swin_base_patch4_window7_224.pth
> ```
> 
> The ImageNet pre-trained model `swin_base_patch4_window7_224.pth` can be downloaded from [this table](https://github.com/microsoft/Swin-Transformer/blob/main/get_started.md#regular-imagenet-1k-trained-models)

https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_base_patch4_window7_224.pth
