### ISSUE TITLE
Question about config files (ade20k.py and schedule_160k.py)

### ISSUE THREAD

**Issue by GokulEpiphany** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#8]
If I'm not mistaken, a couple of config files are yet to be committed. 

1. datasets/ade20k.py
2. schedules/schedule_160k.py

Please do consider committing the above files.

**Comment by impiga** [comment]
Hi, @GokulEpiphany 

Please check this folder: [configs/\_base_](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation/tree/main/configs/_base_)

**Comment by GokulEpiphany** [comment]
Closing this issue..thanks for pointing out the locatio
